version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:3.7.0

jobs:
  test_regression_model_py37:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout:
          path: $PWD
      - run:
          name: Run tests with Python 3.7.0
          command: |
            python -m venv env
            env\Scripts\activate
            sudo pip install --upgrade pip
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py createsuperuser 
workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model_py37