version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:3.5.4
  working_directory: ~/

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox
jobs:
  test_regression_model_py35:
    docker:
      - image: circleci/python:3.5.4
    working_directory: ~/project/model
    steps:
      - checkout:
          path: ~/
      - run:
          name: Run tests with Python 3.5
          command: |
            sudo pip install --upgrade pip
            pip install tox
            pip install -r requirements.txt
            pytest test
workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model_py35